### ISSUE TITLE
Can't build ciaowasm

### ISSUE THREAD

**Issue by SantiagoVillarroel** [ciao-lang/ciaowasm#1]
## Error message
![error build ciaowasm](https://user-images.githubusercontent.com/70483578/221464621-a46f2dc8-1e84-4b32-9c4b-8c77ec4b0405.png)

## Previous steps
- Installed Emscripten and activated environment variables in the current terminal.
- Installed ciao using the one-liner `curl https://ciao-lang.org/boot -sSfL | sh`
![installation_options](https://user-images.githubusercontent.com/70483578/221465286-153ea2e9-8704-4304-ba76-465b3ec40848.png)
- Fetched ciaowasm using `ciao fetch ciaowasm`
- Tried to build by using `ciao build ciaowasm`

## Looking for missing file
Could not find the folder **.ciao/build-boot** specified in the missing file path in my system.

**Comment by jfmc** [comment]
Thanks for the report.
It seems that `ciaowasm` has issues when Ciao is installed with the one-liner. Could you try manual installation from git sources? For reference, here are the precise steps that we use in our workflow https://github.com/ciao-lang/ciao/blob/master/.github/workflows/build.yml#L72 (let me know if you need help identifying the steps)
